services:
  backend:
    image: weather-fetcher:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.App
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      WeatherDatabase__ConnectionString: "Server=host.docker.internal,1433;Database=weather-data-db;User=sa;Password=password-1234;Encrypt=false;TrustServerCertificate=true"
      WeatherApiClientSettings__ApiKey: ""
      ASPNETCORE_URLS: "http://*:8080"
  db:
    image: weather-fetcher-db:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.Db
    ports:
      - "1433:1433"
      - "1434:1434"
    environment:
      SA_PASSWORD: "password-1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"  
    volumes:
      - database:/var/opt/mssql
  frontend:
    image: weather-fetcher-fe:latest
    build:
      context: ./weather-app
      dockerfile: ../docker/Dockerfile.Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  database:
